### ISSUE TITLE
Getting a simple example to run

### ISSUE THREAD

**Issue by Narigo** [LukaJCB/rxscala-js#1]
Hi there,

I'm probably missing some step or command, but I can't start even the simplest example with `Observable`.

I always get "Uncaught TypeError: Cannot read property 'Observable' of undefined" when trying to run it. I've put up a little project that shows the error:

https://github.com/Narigo/scalajs-fun/tree/simple-rxscala-sample

Maybe you can tell me what's missing? I suspect something in the build.sbt, but I can't see what's missing, looking at your example repositories...

Thanks!

**Comment by LukaJCB** [comment]
Hey, thanks for filing an Issue. 
It seems you didn't include your js-deps file inside the HTML. :) 
It's right next to the fastopt file.
Refer to this tutorial: https://www.scala-js.org/tutorial/basic/

**Comment by Narigo** [comment]
Ah! In the `index-dev.html`! Thanks, I didn't see that... :) Would be a nice to have addition to your docs as well - I didn't need that when trying out this library with ScalaJS: https://github.com/lihaoyi/scala.rx ;)

**Comment by LukaJCB** [comment]
Yeah Scala.Rx doesn't have any jsDependencies, that's why you don't have to include them. 
If you specify jsDependencies in your `build.sbt`, though, you have to include them into your project. That's not exactly a part of RxScala.js, but of the Scala.js ecosystem. Which I assume people are familiar with. :)
